[package]
name = "ayyboy-advance"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
bitmatch = "0.1.1"
eframe = "0.28.1"
egui = "0.28.1"
env_logger = "0.11.4"
log = "0.4.22"
crossbeam-channel = "0.5.13"
