[package]
name = "rom-db"
version = "0.1.0"
edition = "2024"

[dependencies]
zip = { version = "4.0.0", default-features = false, features = ["deflate"] }
gba-core = { path = "../gba-core" }
image = { version = "0.25.6", default-features = false, features = ["png"] }
