name: Publish Screenshot Database

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd rom-db-ui
          npm install

      - name: Prepare screenshots
        run: |
          unzip external/screenshots.zip -d rom-db-ui/public
          ls rom-db-ui/public

      - name: Build Next.js application
        run: |
          cd rom-db-ui
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: rom-db-ui/out
